name: sobanuye docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: checkout
      uses: actions/checkout@v3

    -
      name: Python setup
      uses: actions/setup-python@v3

    -
      name: Install requirements
      run: pip install -r requirements.txt
    -
      run: pip install flake8
      name: Install flake
    -
      name: Run unity test
      run: python3 manage.py test
    -
      name: Static test
      run: flake8 .

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
      name: Checkout
    -
      name: Login todocker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -
      name: Set up Docker hub
      uses: docker/setup-buildx-action@v2

    -
      name: build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sobanuye:latest
        
      
